import test, { expect } from '@playwright/test'

test('Criar um prompt via UI com sucesso', async ({ page }) => {
  const title = `E2E Prompt ${Date.now()}`
  const content = 'Content generated by e2e'

  await page.goto('/new')

  expect(page.getByPlaceholder('Prompt title')).toBeVisible()

  await page.fill('input[name=title]', title)
  await page.fill('textarea[name=content]', content)
  await page.getByRole('button', { name: 'Save' }).click()
  await page.waitForSelector('text=Prompt successfully created.', { state: 'visible', timeout: 15000 })
})
