import test, { expect } from '@playwright/test'

import { prisma } from '@/lib/prisma'

test('Criar um prompt via UI com sucesso', async ({ page }) => {
  const title = `E2E Prompt ${Date.now()}`
  const content = 'Content generated by e2e'

  await page.goto('/new')

  expect(page.getByPlaceholder('Prompt title')).toBeVisible()

  await page.fill('input[name=title]', title)
  await page.fill('textarea[name=content]', content)
  await page.getByRole('button', { name: 'Save' }).click()
  await page.waitForSelector('text=Prompt successfully created.', { state: 'visible', timeout: 15000 })

  expect(page.getByText(title))
})

test('Validar duplicidade de título', async ({ page }) => {
  const title = 'E2E not unique title'
  const content = 'Content generated by e2e'

  await prisma.prompt.deleteMany({ where: { title: title } })
  await prisma.prompt.create({ data: { title: title, content } })
  await prisma.$disconnect()

  await page.goto('/new')

  expect(page.getByPlaceholder('Prompt title')).toBeVisible()

  await page.fill('input[name=title]', title)
  await page.fill('textarea[name=content]', content)
  await page.getByRole('button', { name: 'Save' }).click()

  await page.waitForSelector('text=Prompt already exists.', { state: 'visible', timeout: 15000 })
  await expect(page.getByRole('link', { name: title })).toHaveCount(1)
})
